import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import SideBar from "@/components/SideBar";

const Jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kanban Task Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${Jakarta.className} antialiased`}>
        <div className="min-h-screen md:flex overflow-x-hidden">
          <aside className="hidden md:block w-[260px] shrink-0">
            <SideBar />
          </aside>

          <div className="flex-1 flex flex-col min-w-0">
            <Header />
            <main className="bg-[#f4f7fd] flex-1 overflow-y-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
